version: '3'
services:
  blinglog:
    container_name: blinglog
    image: hlf01/blinglog
    restart: always
    # 不使用端口映射，因为minio服务器和mysql服务器在本地时会使用127.0.0.1作为地址，所以需要直接使用宿主机的网卡
    network_mode: host
    env_file:
      - .env
    command: pipenv run flask run -p 5000 -h 0.0.0.0
